results_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/results_0.0.2"
encryption_key: nvidia_tao

model:
  backbone: resnet_50
  last_stride: 1
  pretrain_choice: self
  pretrained_model_path: /home/ika/yzlm/TwinProject/ReID_Experiments/resnet50_market1501_aicity156.tlt
  input_channels: 3
  input_width: 145
  input_height: 390
  neck: bnneck
  feat_dim: 256
  neck_feat: after
  metric_loss_type: triplet
  with_center_loss: false
  with_flip_feature: false
  label_smooth: true
  pretrain_hw_ratio: 2.0
  id_loss_type: softmax
  id_loss_weight: 1.0
  triplet_loss_weight: 1.0
  no_margin: false
  cos_layer: false
  dropout_rate: 0.2
  reduce_feat_dim: false
  drop_path: 0.1
  drop_out: 0.0
  att_drop_rate: 0.0
  stride_size: [16, 16]
  gem_pooling: false
  stem_conv: false
  jpm: false
  shift_num: 5
  shuffle_group: 2
  devide_length: 4
  re_arrange: true
  sie_coe: 3.0
  sie_camera: false
  sie_view: false
  semantic_weight: 1.0

dataset:
  train_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/data/bounding_box_train"
  test_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/data/bounding_box_test"
  query_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/data/query"
  num_classes: 80
  batch_size: 16
  val_batch_size: 32
  num_workers: 8
  pixel_mean: [0.477, 0.465, 0.464]
  pixel_std: [0.312, 0.297, 0.29]
  padding: 10
  prob: 0.6
  re_prob: 0.6
  sampler: softmax_triplet
  num_instances: 2

train:
  num_gpus: 1
  gpu_ids: [0]
  num_nodes: 1
  seed: 1234
  cudnn:
    benchmark: true
    deterministic: false
  num_epochs: 60
  checkpoint_interval: 10
  validation_interval: 10
  resume_training_checkpoint_path: null
  results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/results_0.0.2/train
  optim:
    name: SGD
    lr_monitor: val_loss
    lr_steps: [40]
    gamma: 0.1
    bias_lr_factor: 1.0
    weight_decay: 0.0005
    weight_decay_bias: 0.0005
    warmup_factor: 0.01
    warmup_iters: 0
    warmup_epochs: 5
    warmup_method: linear
    base_lr: 0.0001
    momentum: 0.9
    center_loss_weight: 0.0005
    center_lr: 0.5
    triplet_loss_margin: 0.3
    large_fc_lr: false
    cosine_margin: 0.5
    cosine_scale: 30.0
    trp_l2: false
  grad_clip: 0.0

evaluate:
  num_gpus: 1
  gpu_ids: [0]
  num_nodes: 1
  checkpoint: ???
  trt_engine: null
  results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/evaluate/
  output_sampled_matches_plot: /home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/evaluate/output_sampled_matches_plot.png
  output_cmc_curve_plot: /home/ika/yzlm/TwinProject/ReID_Experiments/ULIRI/evaluate/output_cmc_curve_plot.png
  test_dataset: null
  query_dataset: null

re_ranking:
  re_ranking: true
  k1: 20
  k2: 6
  lambda_value: 0.3
  max_rank: 10
  num_query: 10