results_dir: "/home/ika/yzlm/TwinProject/CCVID/results"
encryption_key: nvidia_tao

model:
  backbone: resnet_50
  last_stride: 1
  pretrain_choice: "self"
  pretrained_model_path: "/home/ika/Downloads/resnet50_market1501_aicity156.tlt"
  input_channels: 3
  input_width: 128
  input_height: 256
  neck: bnneck
  feat_dim: 256
  neck_feat: after
  metric_loss_type: triplet
  with_center_loss: False
  with_flip_feature: False
  label_smooth: True

dataset:
  train_dataset_dir: "/home/ika/yzlm/TwinProject/CCVID/data/bounding_box_train"
  test_dataset_dir: "/home/ika/yzlm/TwinProject/CCVID/data/bounding_box_test"
  query_dataset_dir: "/home/ika/yzlm/TwinProject/CCVID/data/query"
  num_classes: 75
  batch_size: 64
  val_batch_size: 128
  num_workers: 1
  pixel_mean: [0.444, 0.438, 0.457]
  pixel_std: [0.288, 0.280, 0.275]
  padding: 10
  prob: 0.5
  re_prob: 0.5
  sampler: softmax_triplet
  num_instances: 4

re_ranking:
  re_ranking: True
  k1: 20
  k2: 6
  lambda_value: 0.3

train:
  optim:
    name: Adam
    lr_monitor: val_loss
    lr_steps: [10, 20]
    gamma: 0.1
    bias_lr_factor: 1
    weight_decay: 0.0005
    weight_decay_bias: 0.0005
    warmup_factor: 0.01
    warmup_iters: 10
    warmup_method: linear
    base_lr: 0.00035
    momentum: 0.9
    center_loss_weight: 0.0005
    center_lr: 0.5
    triplet_loss_margin: 0.3
    
  num_epochs: 30
  checkpoint_interval: 5
  validation_interval: 5
  
  seed: 1234
evaluate:
  output_cmc_curve_plot: "/home/ika/yzlm/TwinProject/CCVID/results/evaluate/cmc_curve.png"
  results_dir: "/home/ika/yzlm/TwinProject/CCVID/results/evaluate"