# =================================================================
# ===              TAO Re-Identification Config File            ===
# ===      LTCC Makalesinin Eğitim Stratejisine Göre Ayarlanmış   ===
# =================================================================

# --- Genel Ayarlar ---
model_name: null  # TAO tarafından otomatik doldurulur
encryption_key: nvidia_tao
results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.3 # Eğitim sonuçlarının kaydedileceği ana dizin

# --- WandB Entegrasyonu (İsteğe Bağlı) ---
wandb:
  enable: true
  project: "TAO ReID LTCC-Style" # Proje adını daha açıklayıcı yapabilirsiniz
  entity: ''
  tags:
  - training
  - tao-toolkit
  - ltcc-style
  - sgd
  reinit: false
  sync_tensorboard: false
  save_code: false
  name: "TAO ReID Training - SGD - 384x192" # Deney adını daha açıklayıcı yapabilirsiniz

# =================================================================
# ===                   Model Ayarları                          ===
# =================================================================
model:
  backbone: resnet_50
  last_stride: 1
  pretrain_choice: self
  pretrained_model_path: /home/ika/Downloads/resnet50_market1501_aicity156.tlt
  input_channels: 3
  input_width: 192   # <-- DEĞİŞTİ: Orijinal makalenin kullandığı boyut
  input_height: 384  # <-- DEĞİŞTİ: Orijinal makalenin kullandığı boyut
  neck: bnneck # Re-ID için standart ve iyi çalışan bir yapı
  feat_dim: 256
  neck_feat: after
  metric_loss_type: triplet # <-- ÖNEMLİ: Re-ID'de mAP için kritik olan metrik öğrenme kaybı
  with_center_loss: false # Triplet varken genellikle gerekmez
  with_flip_feature: false
  label_smooth: true
  pretrain_hw_ratio: 2.0
  id_loss_type: softmax
  id_loss_weight: 1.0 # ID kaybının ağırlığı
  triplet_loss_weight: 1.0 # Triplet kaybının ağırlığı (ID kaybı ile dengeli)
  no_margin: false
  cos_layer: false
  dropout_rate: 0.0
  reduce_feat_dim: false
  drop_path: 0.1
  drop_out: 0.0
  att_drop_rate: 0.0
  stride_size:
  - 16
  - 16
  gem_pooling: false
  stem_conv: false
  jpm: false
  shift_num: 5
  shuffle_group: 2
  devide_length: 4
  re_arrange: true
  sie_coe: 3.0
  sie_camera: false
  sie_view: false
  semantic_weight: 1.0

# =================================================================
# ===                 Veri Seti Ayarları                        ===
# =================================================================
dataset:
  train_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/bounding_box_train"
  test_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/bounding_box_test"
  query_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/query"
  num_classes: 77
  batch_size: 32 # <-- DEĞİŞTİ: Görüntü boyutu arttığı için GPU belleği yetmeyebilir. 32 ile başlayın.
  val_batch_size: 64 # <-- DEĞİŞTİ: Değerlendirme için 64 yeterli olacaktır.
  num_workers: 8 # <-- DEĞİŞTİ: Veri yüklemeyi hızlandırmak için. Sisteminizde sorun olursa 4'e düşürün.
  pixel_mean:
  - 0.485 # <-- DEĞİŞTİ: ImageNet standart ortalamaları genellikle daha iyi bir başlangıç noktasıdır.
  - 0.456
  - 0.406
  pixel_std:
  - 0.229 # <-- DEĞİŞTİ: ImageNet standart sapmaları.
  - 0.224
  - 0.225
  padding: 10
  prob: 0.5 # Random Erasing olasılığı
  re_prob: 0.5 # Random Erasing olasılığı
  sampler: softmax_triplet # <-- ÖNEMLİ: Triplet loss için doğru örnekleyici
  num_instances: 4 # <-- ÖNEMLİ: Her ID için bir batch'de bulunacak örnek sayısı

# =================================================================
# ===                    Eğitim Ayarları                        ===
# =================================================================
train:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  seed: 1234
  cudnn:
    benchmark: true # <-- DEĞİŞTİ: Görüntü boyutu sabit olduğu için hızı artırır.
    deterministic: false
  num_epochs: 60 # <-- DEĞİŞTİ: Yeni LR planlayıcısına uygun epoch sayısı
  checkpoint_interval: 10
  validation_interval: 5
  resume_training_checkpoint_path: null
  results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.3/train
  optim:
    name: SGD # <-- DEĞİŞTİ: Makaledeki gibi SGD
    lr_monitor: val_loss
    lr_steps:
    - 40 # <-- DEĞİŞTİ: Eğitimin sonlarına doğru LR düşüşü
    gamma: 0.1
    bias_lr_factor: 1.0
    weight_decay: 0.0005
    weight_decay_bias: 0.0005
    warmup_factor: 0.01
    warmup_iters: 0 # <-- DEĞİŞTİ: warmup_epochs kullanıldığı için bu 0 olmalı.
    warmup_epochs: 10 # <-- DEĞİŞTİ: 10 epoch ısınma, 20 çok uzundu.
    warmup_method: linear
    base_lr: 0.01 # <-- DEĞİŞTİ: SGD için tipik bir başlangıç LR'si. Fine-tune için gerekirse 0.001'e düşürün.
    momentum: 0.9
    center_loss_weight: 0.0005
    center_lr: 0.5
    triplet_loss_margin: 0.3
    large_fc_lr: false
    cosine_margin: 0.5 # Kullanılmıyor, çünkü cos_layer=false
    cosine_scale: 30.0 # Kullanılmıyor
    trp_l2: false
  grad_clip: 0.0 # Gradyan kırpma kapalı

# =================================================================
# ===                 Değerlendirme Ayarları                    ===
# =================================================================
evaluate:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  checkpoint: ??? # TAO tarafından doldurulur
  trt_engine: null
  results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.3/evaluate
  output_sampled_matches_plot: null
  output_cmc_curve_plot: null # <-- DEĞİŞTİ: Hata almamak için null olarak ayarlandı.
  test_dataset: null
  query_dataset: null

# =================================================================
# ===                  Inference Ayarları                       ===
# =================================================================
inference:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  checkpoint: ???
  trt_engine: null
  results_dir: null
  output_file: null
  test_dataset: null
  query_dataset: null

# =================================================================
# ===                    Export Ayarları                        ===
# =================================================================
export:
  results_dir: null
  checkpoint: null
  onnx_file: null
  gpu_id: 0

# =================================================================
# ===                 Re-ranking Ayarları                       ===
# =================================================================
re_ranking:
  re_ranking: true # <-- ÖNEMLİ: Değerlendirme sonuçlarını genellikle %2-%5 oranında iyileştirir.
  k1: 20
  k2: 6
  lambda_value: 0.3
  max_rank: 10
  num_query: 10