results_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.2"
encryption_key: nvidia_tao

model:
  backbone: resnet_50
  last_stride: 1
  pretrain_choice: imagenet
  
  input_channels: 3
  input_width: 192    
  input_height: 384   
  neck: bnneck
  feat_dim: 256
  neck_feat: after
  metric_loss_type: triplet
  with_center_loss: False
  with_flip_feature: False
  label_smooth: True

dataset:
  train_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/bounding_box_train"
  test_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/bounding_box_test"
  query_dataset_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/data/query"
  num_classes: 77     
  batch_size: 64     
  val_batch_size: 64 
  num_workers: 4
  pixel_mean: [0.3876, 0.3765, 0.3694]  
  pixel_std: [0.2889, 0.2876, 0.2882]  
  padding: 10
  prob: 0.5
  re_prob: 0.5
  sampler: softmax_triplet
  num_instances: 8   

re_ranking:
  re_ranking: True
  k1: 20
  k2: 6
  lambda_value: 0.3

train:
  num_gpus: 1
  gpu_ids:
  - 0
  num_nodes: 1
  seed: 1234
  cudnn:
    benchmark: false
    deterministic: true
  num_epochs: 60                    
  checkpoint_interval: 5
  validation_interval: 1
  resume_training_checkpoint_path: null
  results_dir: /home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.2/train
  optim:
    name: SGD                      
    lr_monitor: val_loss
    lr_steps:
    - 20                         
    - 40
    gamma: 0.1
    bias_lr_factor: 1.0
    weight_decay: 0.0005
    weight_decay_bias: 0.0005
    warmup_factor: 0.01
    warmup_iters: 10
    warmup_epochs: 10               
    warmup_method: linear
    base_lr: 0.00035             
    momentum: 0.9
    center_loss_weight: 0.0005
    center_lr: 0.5
    triplet_loss_margin: 0.5        
    large_fc_lr: false
    cosine_margin: 0.35             
    cosine_scale: 64.0            
    trp_l2: true                    
  grad_clip: 1.0                   

evaluate:
  output_cmc_curve_plot: null  # <-- CHANGE THIS
  results_dir: "/home/ika/yzlm/TwinProject/ReID_Experiments/LTCC_ReID/results_0.1.2/evaluate"